### ISSUE TITLE
Camfire Mod Crash the game then we place a Campfire etc.

### ISSUE THREAD

**Issue by Titoo8899** [jbredwards/Campfire-Mod#2]
Hi,
in your new Mod Camfire Mod Version 1.0.0 give it a critical Bug. Then I place a Campfire etc. from your mod then crash the game.
Then I the world new load then was the Campfire place.

Her the Crash Report I hope you can fix it.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  UniversalTweaksCore (UniversalTweaks-1.12.2-1.0.0.jar)
  SecurityCraftLoadingPlugin ([1.12.2]+SecurityCraft+v1.9.4.jar)
  Fluidlogged API Plugin (Fluidlogged-API-v1.9.0.4.1-mc1.12.2.jar)
  Disable Elyctra Degradation (Infinilytra-1.12.2-1.0.0.jar)
  MixinLoader (Locks-1.12.2-3.0.0.jar)
  Campfire Plugin (Campfire-v1.0.0-mc1.12.2.jar)
  MixinBooter (!mixinbooter-7.0.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 12/21/22 5:51 PM
Description: Unexpected error

java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
	at com.TominoCZ.FBP.model.FBPModelHelper.isModelValid(FBPModelHelper.java:33)
	at com.TominoCZ.FBP.handler.FBPEventHandler$1.func_184376_a(FBPEventHandler.java:122)
	at net.minecraft.world.World.func_184138_a(World.java:432)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:376)
	at net.minecraft.world.World.func_180501_a(World.java:361)
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:180)
	at git.jbredwards.campfire.common.item.ItemBlockColored.placeBlockAt(ItemBlockColored.java:28)
	at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:54)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:187)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:467)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.redirect$zbi000$onDoItemUse(Minecraft.java:3375)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at com.TominoCZ.FBP.model.FBPModelTransformer.transform(FBPModelTransformer.java:29)
	at com.TominoCZ.FBP.model.FBPModelHelper.isModelValid(FBPModelHelper.java:23)
	... 23 more
Caused by: java.lang.NullPointerException
	at git.jbredwards.campfire.client.renderer.model.ModelCampfireFire$BakedModel.func_188616_a(ModelCampfireFire.java:101)
	at net.minecraftforge.client.model.MultiLayerModel$MultiLayerBakedModel.func_188616_a(MultiLayerModel.java:152)
	at com.TominoCZ.FBP.model.FBPModelTransformer.transform(FBPModelTransformer.java:23)
	... 24 more

(MixinBooter) Mixins in Stacktrace:
	net.minecraft.client.multiplayer.PlayerControllerMP:
		mod.acgaming.universaltweaks.bugfixes.miningglitch.mixin.UTPlayerPositionMixin (mixins.bugfixes.miningglitch.client.json)
	net.minecraft.client.Minecraft:
		io.socol.betterthirdperson.mixin.MinecraftMixin (mixins.betterthirdperson.json)
		net.geforcemods.securitycraft.mixin.camera.MixinMinecraft (securitycraft.mixins.json)
		de.maxhenkel.voicechat.mixin.MinecraftMixin (voicechat.mixins.json)
	net.minecraft.world.World:
		melonslise.locks.mixin.WorldMixin (mixins.locks.json)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.TominoCZ.FBP.model.FBPModelHelper.isModelValid(FBPModelHelper.java:33)
	at com.TominoCZ.FBP.handler.FBPEventHandler$1.func_184376_a(FBPEventHandler.java:122)
	at net.minecraft.world.World.func_184138_a(World.java:432)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:376)
	at net.minecraft.world.World.func_180501_a(World.java:361)
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:180)
	at git.jbredwards.campfire.common.item.ItemBlockColored.placeBlockAt(ItemBlockColored.java:28)
	at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:54)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:187)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:467)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.redirect$zbi000$onDoItemUse(Minecraft.java:3375)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Titoo8899'/69, l='MpServer', x=-355.62, y=4.00, z=-200.01]]
	Chunk stats: MultiplayerChunkCache: 958, 958
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-258,4,-254), Chunk: (at 14,0,2 in -17,-16; contains blocks -272,0,-256 to -257,255,-241), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 395460 game time, 6951 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 28 total; [EntitySheep['Sheep'/7, l='MpServer', x=-409.54, y=4.00, z=-230.76], EntitySheep['Sheep'/12, l='MpServer', x=-395.72, y=4.00, z=-256.54], EntityVillager['Villager'/13, l='MpServer', x=-399.69, y=5.00, z=-196.72], EntityVillager['Villager'/14, l='MpServer', x=-392.70, y=5.00, z=-196.30], EntityVillager['Villager'/15, l='MpServer', x=-392.31, y=5.00, z=-184.50], EntityVillager['Villager'/16, l='MpServer', x=-394.33, y=5.00, z=-184.93], EntityVillager['Villager'/17, l='MpServer', x=-389.18, y=3.94, z=-170.30], EntityVillager['Villager'/20, l='MpServer', x=-388.04, y=4.50, z=-170.98], EntityPig['Pig'/25, l='MpServer', x=-334.54, y=4.00, z=-274.31], EntityChicken['Chicken'/26, l='MpServer', x=-323.24, y=4.00, z=-161.14], EntityItemLoot['item.item.egg'/27, l='MpServer', x=-323.48, y=4.00, z=-161.39], EntityPig['Pig'/35, l='MpServer', x=-293.26, y=4.00, z=-271.62], EntityChicken['Chicken'/36, l='MpServer', x=-292.87, y=4.00, z=-263.74], EntityBoat['Boat'/38, l='MpServer', x=-296.23, y=3.63, z=-213.92], EntityArmorStand['Armour Stand'/39, l='MpServer', x=-288.50, y=1.00, z=-207.50], EntityArmorStand['Armour Stand'/40, l='MpServer', x=-290.50, y=1.00, z=-207.50], EntityArmorStand['Armour Stand'/41, l='MpServer', x=-292.50, y=1.00, z=-207.50], EntityArmorStand['Armour Stand'/42, l='MpServer', x=-294.50, y=1.00, z=-207.50], BuilderEntityRenderForwarder['entity.mts_entity_renderer.name'/10666, l='MpServer', x=-354.51, y=5.59, z=-200.12], EntityArmorStand['Armour Stand'/43, l='MpServer', x=-296.50, y=1.00, z=-207.50], EntityPainting['Painting'/44, l='MpServer', x=-286.03, y=2.50, z=-224.50], EntityPainting['Painting'/45, l='MpServer', x=-286.03, y=2.50, z=-222.00], EntityPainting['Painting'/45, l='MpServer', x=-286.03, y=2.50, z=-222.00], EntityPainting['Painting'/46, l='MpServer', x=-286.03, y=3.00, z=-218.50], EntityPainting['Painting'/46, l='MpServer', x=-286.03, y=3.00, z=-218.50], EntityArmorStand['Armour Stand'/47, l='MpServer', x=-286.50, y=1.00, z=-207.50], EntityPainting['Painting'/44, l='MpServer', x=-286.03, y=2.50, z=-224.50], EntityPlayerSP['Titoo8899'/69, l='MpServer', x=-355.62, y=4.00, z=-200.01]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2249906312 bytes (2145 MB) / 5570035712 bytes (5312 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 31 mods loaded, 31 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version       | Source                                   | Signature                                |
	|:------ |:----------------- |:------------- |:---------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft         | 1.12.2        | minecraft.jar                            | None                                     |
	| LCHIJA | mcp               | 9.42          | minecraft.jar                            | None                                     |
	| LCHIJA | FML               | 8.0.99.99     | forge-1.12.2-14.23.5.2860.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge             | 14.23.5.2860  | forge-1.12.2-14.23.5.2860.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | mixinbooter       | 7.0           | minecraft.jar                            | None                                     |
	| LCHIJA | boatoverhaul      | 1.0           | BoatOverhaul-Forge-1.12.2-1.1.0.jar      | None                                     |
	| LCHIJA | securitycraft     | v1.9.4        | [1.12.2]+SecurityCraft+v1.9.4.jar        | None                                     |
	| LCHIJA | timelesspower     | 1.2           | [1.12.2]TimelessPower-1.2.jar            | None                                     |
	| LCHIJA | betterthirdperson | 1.9.0         | BetterThirdPerson-Forge-1.12.2-1.9.0.jar | None                                     |
	| LCHIJA | campfire          | 1.0.0         | Campfire-v1.0.0-mc1.12.2.jar             | None                                     |
	| LCHIJA | configuration     | 1.0.3.1       | configuration-1.12.2-1.0.3.1.jar         | None                                     |
	| LCHIJA | darkstone         | 1.12.2-1.0    | darkstone-1.12.2-1.0.jar                 | None                                     |
	| LCHIJA | fbp               | 0.7           | fbp-0.7.jar                              | None                                     |
	| LCHIJA | fcl               | 1.12.77       | FCL-1.12.77-1211221915.jar               | None                                     |
	| LCHIJA | frl               | 1.2           | FCL-1.12.77-1211221915.jar               | None                                     |
	| LCHIJA | tmt               | 1.15          | FCL-1.12.77-1211221915.jar               | None                                     |
	| LCHIJA | firstaid          | 1.6.21        | firstaid-1.6.21.jar                      | 7904c4e13947c8a616c5f39b26bdeba796500722 |
	| LCHIJA | fluidlogged_api   | 1.9.0.4       | Fluidlogged-API-v1.9.0.4.1-mc1.12.2.jar  | None                                     |
	| LCHIJA | fsmm              | 2.6.2         | FSMM-2.6.2 (1).jar                       | None                                     |
	| LCHIJA | mts               | 22.4.0-BETA1  | Immersive+Vehicles-1.12.2-22.4.0.jar     | None                                     |
	| LCHIJA | keywizard         | 1.12.2-1.7.3  | keywizard-1.12.2-1.7.3.jar               | None                                     |
	| LCHIJA | laa_tailoring     | 1.0.0         | laa-tailoring.jar                        | None                                     |
	| LCHIJA | locks             | 3.0.0         | Locks-1.12.2-3.0.0.jar                   | None                                     |
	| LCHIJA | pcmds             | 1.0           | Payable+Command+Signs-1.0.jar            | None                                     |
	| LCHIJA | payday            | 3.0           | payday-3.2-1.12.2.jar                    | None                                     |
	| LCHIJA | quickstore        | 1.4           | quickstore-1.5.jar                       | None                                     |
	| LCHIJA | jianghun          | 1.0           | RGB+Chat+0.5.jar                         | None                                     |
	| LCHIJA | snowtime          | 1.0-SNAPSHOT  | snowtime-1.0-SNAPSHOT.jar                | None                                     |
	| LCHIJA | universaltweaks   | 1.12.2-1.0.0  | UniversalTweaks-1.12.2-1.0.0.jar         | None                                     |
	| LCHIJA | voicechat         | 1.12.2-2.3.24 | voicechat-forge-1.12.2-2.3.24.jar        | None                                     |
	| LCHIJA | ignitingarrows    | 1.12.2-INDEV  | IgnitingArrows-1.12.2-1.0.0.jar          | None                                     |

	Loaded coremods (and transformers): 
UniversalTweaksCore (UniversalTweaks-1.12.2-1.0.0.jar)
  
SecurityCraftLoadingPlugin ([1.12.2]+SecurityCraft+v1.9.4.jar)
  
Fluidlogged API Plugin (Fluidlogged-API-v1.9.0.4.1-mc1.12.2.jar)
  git.jbredwards.fluidlogged_api.mod.asm.ASMHandler$Transformer
Disable Elyctra Degradation (Infinilytra-1.12.2-1.0.0.jar)
  staples.infinilytra.asm.transformer.EntityLivingBaseTransformer
MixinLoader (Locks-1.12.2-3.0.0.jar)
  
Campfire Plugin (Campfire-v1.0.0-mc1.12.2.jar)
  git.jbredwards.campfire.asm.ASMHandler$Transformer
MixinBooter (!mixinbooter-7.0.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 527.56' Renderer: 'NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: 1.12.2-forge-14.23.5.2860
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 527.56, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (United Kingdom)
	Profiler Position: N/A (disabled)
	CPU: 6x Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz

**Comment by jbredwards** [comment]
this crash is caused by the fancier block particles mod, add campfires to that mod's blacklist files until they fix the issue
